### ISSUE TITLE
Cannot receive complete "data" object from OAuth flow

### ISSUE THREAD

**Issue by hansemannn** [Capevace/passport-apple-sign-in#1]
Hey @Capevace, 

first of all, thank you for jumping in to support Apple Sign In functionality at this early point!

I have tested your integration and the flow itself works great. One thing I noticed though is I am not able to receive the "data" object returned from the authorization action, e.g.
```json
{
  "access_token": "<>",
  "token_type": "Bearer",
  "expires_in": 3600,
  "refresh_token": "<>",
  "id_token": "<>"
}
```
which is passed to the callback [here](https://github.com/Capevace/passport-apple-sign-in/blob/master/lib/strategy.js#L85) but unfortunately is an empty object when returned to
```js
passport.use(
  new AppleSignInStrategy({ ... },
    function(accessToken, refreshToken, expires_in, profileData, done) {
    	this is empty  -----------------------------^
    }
  )
);
```
Have you by any chance experienced the same? I feel like it's the order of the callback arguments, because it works when passing it as thee 3rd parameter.

Thanks in advance!

**Comment by Capevace** [comment]
Hey!

I have an idea where that bug might be coming from. When I first wrote this library the endpoints weren’t actually live yet so I simply wrote it to spec. I’ll have a look if maybe the spec has changed since then and will try to test it out sometime next week if I find the time! :)

Regards,
Lukas

**Comment by hansemannn** [comment]
Thanks Lukas, really appreciate it!

**Comment by hansemannn** [comment]
It seems like [@nicokaiser/passport-apple](https://www.npmjs.com/package/@nicokaiser/passport-apple) solved it already!

**Comment by kfir2037** [comment]
> Hey!
> 
> I have an idea where that bug might be coming from. When I first wrote this library the endpoints weren’t actually live yet so I simply wrote it to spec. I’ll have a look if maybe the spec has changed since then and will try to test it out sometime next week if I find the time! :)
> 
> Regards,
> Lukas

Hi,
 do you have a solution to this problem? 
I tried to figure it out my swelf but but with no success
